### ISSUE TITLE
28 Day NASR Subscription Files

### ISSUE THREAD

**Issue by ktjaco** [antoniolocandro/aeronautical_charting#13]
Hi Antonio,

Thank you for your video series and tutorials on aeronautical charting. They are very helpful!

I am currently working with the 28 Day NASR Subscription File (AIXM 5.1) found here: https://nfdc.faa.gov/webContent/28DaySub/2021-02-25/aixm5.1.zip

When I download the files the one XML with spatial reference is Designated Points. Is this normal? Or are there additional transformations that have to be done to the data? I noticed some files have a "pos" field for latitude/longitude. 

Any further information or help is much appreciated!

https://www.faa.gov/air_traffic/flight_info/aeronav/aero_data/NASR_Subscription_2021-02-25/

**Comment by antoniolocandro** [comment]
Hi this would be specific to FAA data you may want to see if they have a mailing list, repository or a contact form. I will see if I can at least check why it is not read by GDAL which is what QGIS uses to try to read the geometries
